name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $GITHUB_WORKSPACE

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
      - name: Stable
        run: cargo check

      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets

  check-macos-arm:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Install target
        run: rustup update && rustup target add aarch64-apple-darwin
      - name: Check build
        run: cargo check --target=aarch64-apple-darwin
